pipeline {
	options {
		timeout (200)
    }
    agent any
	
    stages {
        stage('pull code') {
            steps {
				timeout(time: 30, unit: 'MINUTES'){
                echo '开始拉取代码'
                checkout([$class: 'GitSCM', branches: [[name: '*/main']], extensions: [], userRemoteConfigs: [[credentialsId: 'cb3ae9aa-a44b-4b2c-a972-50e3706891fb', url: 'https://github.com/jirufeng24/310442608.git']]])
                echo '拉取代码结束'
				}
            }
        }
		stage('run jflash program') {
			steps {
			    echo 'Jflash开始烧录'
				bat """robot --pythonpath . --include test C:\\ProgramData\\Jenkins\\.jenkins\\workspace\\chinaGateway_cloud_regression_SCM\\CIScriptFiles\\chinaGateway\\Pocket Cloud 回归\\Clould 回归\\RF_demo"""
				echo 'Jflash脚本运行结束'
			}
		}   
    }
}