on:
  workflow_dispatch:
  schedule:
name: nightly
jobs:
  nightly:
    runs-on: windows-latest
    steps:
      - name: Build
        run: date

  notification:
    if: ${{ success() || failure() }}
    # Add a dependency to the nightly job
    needs: nightly

    runs-on: windows-latest
    permissions:
          issues: write
    steps:
      - name: Notification via issue comment
        if: ${{ success() || failure() }}
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: 119,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `New nightly build: ${{ needs.nightly.result }}
              * Date: ${{ steps.get_date.outputs.DATE }}
              * Branch: ${{ github.ref_name }}
              * Link: https://github.schneider-electric.com/ShenNong/dcm
              * Latest commit id: ${{ github.sha }}
              * Actions: https://github.schneider-electric.com/ShenNong/dcm/actions/runs/${{ github.run_id }}
              * Nightly package: https://jfrog-apac.se.com/ui/repos/tree/General/shennong-develop-generic-prod-fed/nightly?projectKey=shennong
              * Notification: @SESA627952 @SESA657209`
            })
