name: Email test

on: 
    workflow_dispatch:
    
jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    - name: Send an email
      uses: actions/email@v6
      with:
        to: rufeng.ji@non.se.com
        subject: The script has been run
        body: The script has completed successfully. 
