name: nightly
on:
  workflow_dispatch:
    inputs:
      isBurn:
        type: boolean
        description: Need to burn the version?
        default: False
      versionNumber: 
        type:  string
        description: Enter the target version number.    
        default: '1.1.6' 
      isConnected:
        type: boolean
        required: True
        description: Is the ETU device connected?
      tagName:
        type: choice
        description: Select the TAG that needs to be executed.
        options:
        - Modbus
        - ULP command
        - All
        default: 'Modbus'

jobs:
  execute_test_case:
    runs-on:  windows-latest
    steps:
      # - name: step1:- pull case script/library.
      #   uses: actions/checkout@v3
      #   with:
      #     ref: main
            
      - name: step1:-Checkout the case's scripts.
        run: |
          echo 11111111111111111111111111
          echo ${{isBurn}}
          echo ${{versionNumber}}
          echo ${{ isConnected }}
          echo ${{ tagName }}
