name: Email test

on: 
    workflow_dispatch:
    
jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    - name: do something
      run: |
        echo 11111111111111111
        date
    - name: Send an email
      # run: |
      #   echo 2222222222222222
      #   date
      uses: actions/email@v2
      with:
        to: rufeng.ji@non.se.com
        subject: The script has been run
        body: The script has completed successfully. 
