name: test actions
on:
  workflow_dispatch:
    inputs:
      isBurn:
        type: boolean
        description: Need to burn the version?
        default: False
      versionNumber: 
        type:  string
        description: Enter the target version number.    
        default: '1.1.6' 
      isConnected:
        type: boolean
        required: True
        description: Is the ETU device connected?
      tagName:
        type: choice
        description: Select the TAG that needs to be executed.
        options:
        - Modbus
        - ULP command
        - All
        default: 'Modbus'

jobs:
  execute_test_case:
    runs-on:  windows-latest
    steps:
      - name: step0:-Checkout the case's scripts.
        run: |
          echo 11111111111111111111111111
          echo "isBurn: ${{ github.event.inputs.isBurn }}"
          echo "versionNumber: ${{ github.event.inputs.versionNumber }}"
          echo "isConnected: ${{ github.event.inputs.isConnected }}"
          echo "tagName: ${{ github.event.inputs.tagName }}"
          
      - name: step1:- pull case script/library.
        uses: actions/checkout@v3
        with:
          ref: main

      - name: step2:-Install the required libraries.
        run: |
          echo 开始检查安装case脚本依赖的库和类
          # pip install -r .\CIScriptFiles/requirements.txt
          echo 安装case脚本依赖库结束
      - name: step3:-Run the testcase script.
        run: |
          echo 开始脚本执行
          pytest
          echo 回归案例脚本执行结束



            
      
