name: Email test

on: workflow_dispatch:
    version_number: 
          description: 'input the version number of gateway.'      
          required: true 
          default: 'v1.17.06' 
        is_burn:
          type: boolean
          description: True or False
        choice:
          type: choice
          description: Make a choice
          options:
          - hub
          - cloud
          - hub&cloud

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    - name: Send an email
      uses: actions/email@v2
      with:
        to: rufeng.ji@non.se.com
        subject: The script has been run
        body: The script has completed successfully. 
