on:
  workflow_dispatch:
name: nightly
jobs:
  nightly:
    runs-on: windows-latest
    steps:
      - name: Build
        run: date

  notification:
    if: ${{ success() || failure() }}
    # Add a dependency to the nightly job
    needs: nightly

    runs-on: windows-latest
    permissions:
          issues: write
    steps:
      - name: Notification via issue comment
        if: ${{ success() || failure() }}
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: 119,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `New nightly build: 1111
              * Link: https://github.schneider-electric.com/ShenNong/dcm
              * Notification: @SESA627952 @SESA657209`
            })
